sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动名称
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "HUNter0409"
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t94YrdJHRH8fknrojnE
    access-key-secret: 5CQJOQVTWBCthPks8jUZUe0MiM72yb
    bucket-name: sky-take-out-523
